collections:
  free-offerings: 
    output: true
    permalink: /:slug
overlay_style: none
_inputs:
  overlay_style:
    type: select
    options:
      values:
        - none
        - light
        - medium
        - dark