seo:
  site_name: Mana Mei
  title: International Feminine Embodiment Leader
  description: 
  keywords: 
  social_image: 
  author: Embodied Creative
social:
  instagram_username: manamei_movement
navigation:
  - url: "/index.html"
    title: "Home"
  - url: "/about.html"
    title: "Meet Mana"
  - url: "/offerings.html"
    title: "Offerings"
navigation-footer:
  - url: "/liberation-through-movement.html"
    title: "Liberation Through Movement"
  - url: "/mana-movement-foundations.html"
    title: "Mana Movement Foundations"
  - url: "/mana-movement.html"
    title: "Mana Movement"    
  - url: "/wisdom-body.html"
    title: "Wisdom Body"
  - url: "/nectar-series.html"
    title: "Nectar Series"    
  - url: "/liberation-through-movement-mentorship.html"
    title: "Liberation Through Movement Mentorship"
navigation-instagram:
  - url: "/liberation-through-movement.html"
    title: "Liberation Through Movement"
  - url: "/mana-movement-foundations.html"
    title: "Mana Movement Foundations"
  - url: "/mana-movement.html"
    title: "Mana Movement"    
  - url: "/wisdom-body.html"
    title: "Wisdom Body"
  - url: "/nectar-series.html"
    title: "Nectar Series"    
  - url: "/liberation-through-movement-mentorship.html"
    title: "Liberation Through Movement Mentorship"
  - url: "/index.html"
    title: "Website"