seo:
  site_name: Mana Mei
  title: Mana Mei - Liberation Through Movement Founder, International Feminine Embodiment Leader
  description: Discover the transformative power of feminine embodiment with Mana Mei. Explore our unique blend of movement, dance, and somatic practices designed to empower women through self-expression and bodily liberation. Join our global community and awaken your inner strength.
  keywords: Mana Mei, feminine embodiment, liberation through movement, somatic dance, empowerment, self-expression, movement founder, international feminine embodiment leader, feminine power, embodied movement
  social_image: /uploads/icons/manamei-11.png
  author: Embodied Creative
social:
  instagram_username: manamei_movement
navigation:
  - url: "/index.html"
    title: "Home"
  - url: "/about.html"
    title: "Meet Mana"
  - url: "/offerings.html"
    title: "Offerings"
navigation-footer:
  - url: "/liberation-through-movement.html"
    title: "Liberation Through Movement"
  - url: "/mana-movement-foundations.html"
    title: "Mana Movement Foundations"
  - url: "/mana-movement.html"
    title: "Mana Movement"    
  - url: "/wisdom-body.html"
    title: "Wisdom Body"    
  - url: "/liberation-through-movement-mentorship.html"
    title: "Liberation Through Movement Mentorship"
navigation-instagram:
  - url: "/liberation-through-movement.html"
    title: "Liberation Through Movement"
  - url: "/mana-movement-foundations.html"
    title: "Mana Movement Foundations"
  - url: "/mana-movement.html"
    title: "Mana Movement"    
  - url: "/wisdom-body.html"
    title: "Wisdom Body"    
  - url: "/liberation-through-movement-mentorship.html"
    title: "Liberation Through Movement Mentorship"
  - url: "/index.html"
    title: "Website"