seo:
  site_name: Mana Mei
  title: International Feminine Embodiment Leader
  description: 
  keywords: 
  social_image: 
  author: Embodied Creative
social:
  instagram_username: manamei_movement
navigation:
  - url: "/index.html"
    title: "Home"
  - url: "/about.html"
    title: "Meet Mana"
  - url: "/offerings.html"
    title: "Offerings"    
  - url: "/contact.html"
    title: "Contact"
navigation-footer:
  - url: "/offerings/liberation-through-movement.html"
    title: "Liberation Through Movement"
  - url: "/offerings/mana-movement-foundations.html"
    title: "Mana Movement Foundations"
  - url: "/offerings/mana-movement.html"
    title: "Mana Movement"    
  - url: "/offerings/wisdom-body.html"
    title: "Wisdom Body"
  - url: "/offerings/nectar-series.html"
    title: "Nectar Series"    
  - url: "/offerings/liberation-through-movement-membership.html"
    title: "Liberation Through Movement Membership"